version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: SpacecatsmarketDB
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: SpacecatsmarketDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: haP17PY
